BEGIN TRANSACTION;
DROP TABLE IF EXISTS PRODUTOS
CREATE TABLE PRODUTOS(
    PRODUTO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUTO_NOME TEXT NOT NULL,
    PRODUTO_VALOR_UNITARIO INTEGER
   );

DROP TABLE IF EXISTS PRATELEIRAS
CREATE TABLE PRATELEIRAS(
    PRATELEIRA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRATELEIRA_NOME TEXT NOT NULL,
    PRATELEIRA_LOCALIZACAO TEXT NOT NULL
   );

DROP TABLE IF EXISTS CUPOMFISCAL
CREATE TABLE CUPOMFISCAL(
    CUPOMFISCAL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CUPOMFISCAL_DATA TEXT NOT NULL,
    CUPOMFISCAL_NUMERO  INTERGER,
    CUPOMFISCAL_CLIENTE_ID INTEGER NOT NULL
   ); 





INSERT INTO PRODUTOS ( PRODUTO_ID, PRODUTO_NOME, PRODUTO_VALOR_UNITARIO)
    VALUES
    ('CAMPO GRANDE'),
    ('BLUMENAU'),
    ('FLORIANOPOLIS'),
    ('SAO PAULO'),
    ('JOINVILLE');

    INSERT INTO PESSOAS (PESSOA_NOME, PESSOA_IDADE, PESSOA_CIDADE_ID)
        VALUES
        ('Adriano Machado', 47, 1),
        ('Karina Machado', 45, 1),
        ('Carlos Machado', 50, 5),
        ('Pedro Silva', 20, 2),
        ('Tia Zefinha', 60, 3),
        ('Adriano Machado', 47, 5);

    COMMIT;

    SELECT * FROM CIDADES;
    SELECT * FROM PESSOAS;