SELECT PRATELEIRA_NOME, PRATELEIRA_LOCALIZACAO FROM PRATELEIRAS; 
 
SELECT PRODUTO_CODIGO,PRODUTO_NOME,PRODUTO_QUANTIDADE,PRODUTO_VALOR 
FROM PRODUTOS ORDER BY PRODUTO_CODIGO; 
 
SELECT NOTA_ID, NOTA_DATA_DE_EMISSÃO FROM NOTAS; 
 
SELECT ITEN_CUPOM_FISCAL_PRODUTO, ITEN_CUPOM_FISCAL_VALOR_UN, ITEN_CUPOM_FISCAL_VALOR_TOT  
FROM ITENS_CUPOM_FISCAL; 
 
SELECT CLIENTE_NOME FROM CLIENTES; 
 
SELECT ATENDENTE_NOME FROM ATENDENTES;



