SELECT PRATELEIRA_NOME, PRATELEIRA_LOCALIZACAO FROM PRATELEIRAS; 
 
SELECT PRODUTO_CODIGO,PRODUTO_NOME,PRODUTO_QUANTIDADE,PRODUTO_VALOR 
FROM PRODUTOS ORDER BY PRODUTO_CODIGO; 
 
SELECT NOTA_DATA_DE_EMISSAO,ITEN_CUPOM_FISCAL_PRODUTO, ITEN_CUPOM_FISCAL_VALOR_UN, ITEN_CUPOM_FISCAL_VALOR_TOT  
FROM ITENS_CUPOM_FISCAL,NOTAS
WHERE ITEN_CUPOM_FISCAL_NUMERO = 1000 AND NOTA_ID=1000; 
 
SELECT CLIENTE_NOME FROM CLIENTES; 
 
SELECT ATENDENTE_NOME FROM ATENDENTES;