BEGIN TRANSACTION;
DROP TABLE IF EXISTS CIDADES;
CREATE TABLE CIDADES (
    CIDADES_ID INTERGER PRIMARY KEY AUTOINCREMENT,
    CIDADES_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;
CREATE TABLE PESSOAS(
    PESSOAS_ID INTERGER, PRIMARY KEY AUTOINCREMENT,
    PESSOAS_NOME TEXT NOT NULL,
    PESSOAS_IDADE INTERGER,
    PESSOAS_CIDADES_ID INTERGER NOT NULL
);


INSERT INTO CIDADES (CIDADES_NOME)
    VALUES
    ('CAMPO GRANDE'),
    ('BLUMENAU'),
    ('FLORIANOPOLIS'),
    ('SAO PAULO'),
    ('JOINVILLE');

    INSERT INTO PESSOAS (PESSOAS_NOME, PESSOAS_IDADE, PESSOAS_CIDADES)
        VALUES
        ('Adriano Machado', 47, 1),
        ('Karina Machado', 45, 1),
        ('Carlos Machado', 50, 5),
        ('Pedro Silva', 20, 2),
        ('Tia Zefinha', 60, 3);
        ('Adriano Machado', 47, 5),

    COMMIT;

    SELECT * FROM CIDADES;
    SELECT * FROM PESSOAS;
    