BEGIN TRANSACTION;
DROP TABLE IF EXISTS CIDADES;
CREATE TABLE CIDADES (
    CIDADE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADE_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;
CREATE TABLE PESSOAS(
    PESSOA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PESSOA_NOME TEXT NOT NULL,
    PESSOA_IDADE INTERGER,
    PESSOA_CIDADE_ID INTEGER NOT NULL 
);


INSERT INTO CIDADES (CIDADE_NOME)
    VALUES
    ('CAMPO GRANDE'),
    ('BLUMENAU'),
    ('FLORIANOPOLIS'),
    ('SAO PAULO'),
    ('JOINVILLE');

    INSERT INTO PESSOAS (PESSOA_NOME, PESSOA_IDADE, PESSOA_CIDADE_ID)
        VALUES
        ('Adriano Machado', 47, 1),
        ('Karina Machado', 45, 1),
        ('Carlos Machado', 50, 5),
        ('Pedro Silva', 20, 2),
        ('Tia Zefinha', 60, 3),
        ('Adriano Machado', 47, 5);

    COMMIT;

    SELECT * FROM CIDADES;
    SELECT * FROM PESSOAS;
    

    