SELECT * FROM PESSOAS;
SELECT * FROM CIDADES;

SELECT PESSOAS_NOME,PESSOAS_IDADE
FROM PESSOAS;

SELECT DISTINCT(PESSOAS_NOME)
FROM PESSOAS  

SELECT * FROM PESSOAS WHERE PESSOAS_NOME LIKE '%ADRIAN';

SELECT * FROM PESSOAS WHERE PESSOAS_IDADE BETWEEN 45 AND 50;

SELECT PESSOAS_IDADE,PESSOAS_NOME FROM PESSOAS ORDER BY PESSOAS_IDADE,PESSOAS_NOME;

SELECT PESSOAS_IDADE,PESSOAS_NOME FROM PESSOAS ORDER BY PESSOAS_IDADE DESC;

SELECT AVG(PESSOAS_IDADE) FROM PESSOAS;

SELECT MIN(PESSOAS_IDADE) FROM PESSOAS;

SELECT MAX(PESSOAS_IDADE) FROM PESSOAS;

SELECT COUNT(*) FROM PESSOAS;

SELECT PESSOAS_IDADE, COUNT(PESSOAS_NOME)
FROM PESSOAS
GROUP BY PESSOAS_IDADE;

SELECT.CIDADES_NOME,
PESSOAS.PESSOAS_NOME,
PESSOAS.PESSOAS_IDADE
FROM
PESSOAS,CIDADES
WHERE PESSOAS.PESSOAS_CIDADE_ID = CIDADES.CIDADES_ID;

